import { BORDER_GREY, BUTTON_RED_ACTIVE, COLOR_DISABLED, FONT_GREEN_PRIMARY, FONT_GREY_PRIMARY, FONT_GREY_SECONDARY, FONT_RED_PRIMARY } from "../../../styles/index";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    layout: {
        flex: 1, 
        paddingVertical: 20, 
        backgroundColor: 'white', 
        paddingHorizontal: 24
    },
    container: { flex: 1, backgroundColor: '#FAFAF9'},
    imageBackgroundStyle: {
        width: '100%', 
        height: 320, 
        backgroundColor: '#FAFAF9', 
        paddingTop: 50
    },
    viewTop: {width: '100%', height: '100%', paddingHorizontal: 20},
    usernameStyle: {justifyContent: 'space-between', alignItems: 'center', flexDirection: 'row'},
    textUsername: {marginLeft: 10, fontSize: 16, fontFamily: 'Inter-Regular', color: 'white'},
    notifStyle: {backgroundColor: 'white', height: 34, width: 34, marginRight: 2, borderRadius: 50, justifyContent: 'center', alignItems: 'center'},
    cardSaldo: {flex: 1, backgroundColor: 'white', width: '100%', borderRadius: 12, marginTop: 24, elevation: 2, paddingHorizontal: 20, paddingBottom: 20, paddingTop: 20},
    viewTitleSaldo: {flex: 1, width: '100%', flexDirection: 'row', height: 40, alignItems: 'center', justifyContent: 'space-between'},
    viewTopLeft: {flexDirection: 'row', width: '70%'},
    textSaldoAnda: {fontSize: 14, fontFamily: 'Inter-Regular', color: FONT_GREY_PRIMARY, marginLeft: 8},
    tmoneyLogoStyle: {width: '24%', height: '100%'},
    viewSaldoNominal: {flex: 1, flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'flex-start'},
    textIdr: {fontFamily: 'Inter-Bold', color: FONT_GREY_SECONDARY, fontSize: 14},
    textNominal: {fontFamily: 'Inter-Bold', color: FONT_GREY_SECONDARY, fontSize: 34},
    viewCardMenu: {flex: 1, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end'},
    viewIconCard: {justifyContent: 'center', alignItems: 'center'},
    viewMenuItem: {width: 40, height: 40, justifyContent: 'center', alignItems: 'center'},
    textMenuItem: {fontSize: 12, fontFamily: 'Inter-Regular', color: FONT_GREY_PRIMARY, marginTop: 2},
    alertVerif: {
        height: 80,
        backgroundColor: '#FFFAEB', 
        flexDirection: 'row', 
        justifyContent: 'center', 
        alignItems: 'center', 
        paddingVertical: 14, 
        paddingHorizontal: 24,
        marginHorizontal: 20, 
        marginTop: 5, 
        elevation: 2, 
        borderRadius: 8,
    },
    viewAlertLeft: {width: '95%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
    textDescAlert: {width: '75%'},
    iconLeft: {width: '17%', justifyContent: 'center', alignItems: 'flex-start'},
    arrowRight: {width: '5%', justifyContent: 'flex-end', alignItems: 'flex-end'},
    bottomSheetStyle: {
        marginTop: 8, 
        paddingTop: 12, 
        borderTopLeftRadius: 14, 
        borderTopRightRadius: 14,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 6,
        },
        shadowOpacity: 0.37,
        shadowRadius: 7.49,
        elevation: 12,
    },
    contentContainerStyle: {flexGrow: 1, paddingTop: 20, paddingBottom: 50, paddingHorizontal: 20},
    bottomSheetTopMenu: {flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', marginBottom: 24},
    viewBottomSheetMenu: {justifyContent: 'center', alignItems: 'center', width: '25%'},
    viewBottomSheetIcon: {width: 40, height: 40, justifyContent: 'center', alignItems: 'center', marginBottom: 12},
    bottomSheetMidMenu: {flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center'},
    bottomSheetBottomMenu: {marginTop: 40},
    viewTitleBottomView: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
    textStyle: {fontSize: 14, fontFamily: 'Inter-Bold', color: FONT_GREY_SECONDARY},
    viewStyle: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center'},
    textLihatSemua: {fontSize: 14, fontFamily: 'Inter-Regular', color: FONT_RED_PRIMARY, marginRight: 10},
    viewTransaksiItem: {
        backgroundColor: 'white', 
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        alignItems: 'center', 
        paddingVertical: 14, 
        paddingHorizontal: 16,
        marginTop: 20, 
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#D9D9D9'
    },
    viewItemDetail: {alignItems: 'flex-start', justifyContent: 'center'},
    textDateTransaksi: {fontSize: 12, fontFamily: 'Inter-Regular', color: FONT_GREY_SECONDARY},
    textNominalSukses: {fontSize: 12, fontFamily: 'Inter-Bold', color: FONT_GREEN_PRIMARY},
    textNominalFail: {fontSize: 12, fontFamily: 'Inter-Bold', color: FONT_RED_PRIMARY},
    btnStyle: {
        backgroundColor: BUTTON_RED_ACTIVE, 
        width: '48%', 
        padding: 16, 
        alignContent: 'center', 
        alignItems: 'center', 
        justifyContent: 'center', 
        borderRadius: 8,
        alignSelf: 'flex-end'
    },
    btnStyle2: {
        backgroundColor: 'white',
        borderWidth: 1, 
        borderColor: FONT_RED_PRIMARY,
        width: '48%', 
        padding: 16, 
        alignContent: 'center', 
        alignItems: 'center', 
        justifyContent: 'center', 
        borderRadius: 8,
        alignSelf: 'flex-end'
    },
    btnStyle3: {
        backgroundColor: BUTTON_RED_ACTIVE, 
        width: '100%', 
        padding: 16, 
        alignContent: 'center', 
        alignItems: 'center', 
        justifyContent: 'center', 
        borderRadius: 8,
        alignSelf: 'flex-end'
    },
    textButton: { color: 'white', fontFamily: 'Inter-Bold' },
    textButton2: { color: FONT_RED_PRIMARY, fontFamily: 'Inter-Bold' },
    modalStyle: {flex: 1, margin: 0},
    viewModal: {
        width: '100%', 
        height: 460,
        backgroundColor: 'white',
        borderTopRightRadius: 28,
        borderTopLeftRadius: 28,
        padding: 24,
        position: 'absolute',
        bottom: 0,
    },
    viewModal2: {
        width: '100%', 
        height: 260,
        backgroundColor: 'white',
        borderTopRightRadius: 28,
        borderTopLeftRadius: 28,
        padding: 24,
        position: 'absolute',
        bottom: 0,
    },
    titleStyle: {
        fontSize: 20, 
        color: FONT_GREY_PRIMARY, 
        fontFamily: 'NunitoSans-Bold',
        marginTop: 10,
        marginLeft: 8
    },
    subTitleStyle: {
        fontSize: 16, 
        color: FONT_GREY_PRIMARY, 
        fontFamily: 'NunitoSans-Regular', 
        marginHorizontal: 8,
        marginTop: 16,
        textAlign: 'center'
    },
    subTitleStyle2: {
        fontSize: 16, 
        color: FONT_GREY_PRIMARY, 
        fontFamily: 'NunitoSans-Regular', 
        marginHorizontal: 8,
        marginTop: 16,
        textAlign: 'left'
    },
    viewBtn: {flex: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 5},
    viewBtn2: {flex: 1, justifyContent: 'flex-end', alignItems: 'center', paddingHorizontal: 5},
    viewGrip: {width: '100%', justifyContent: 'center', alignItems: 'center', marginVertical: 10},
    scrollContentStyle: {width: '100%', height: 330, backgroundColor: '#FAFAF9'},
    modalImage: {justifyContent: "center", alignItems: 'center', width: '80%', height: 200, marginTop: 20, alignSelf: 'center'},
    modalVerifEmailSukses: {flex: 1, margin: 0, alignItems: 'center', justifyContent: 'flex-start', marginTop: 20},
    imageModalStyle: {width: '100%', height: '100%'},
    verifikasiEmail: {
        flexDirection: 'row',
        height: 80, 
        width: '95%',
        elevation: 5, 
        justifyContent: 'center', 
        alignItems: 'center', 
        backgroundColor: 'white', 
        borderRadius: 8, 
        paddingVertical: 10, 
        paddingHorizontal: 20
    },
    textVerifEmail: {width: '90%', fontSize: 14, color: FONT_GREY_PRIMARY, fontFamily: 'Inter-Bold'},
});

export default styles;